spring.application.name=planchella
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/planchella
spring.datasource.username=nour
spring.datasource.password=12345
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=update

# spring.security.oauth2.client.registration.google.client-id=
# spring.security.oauth2.client.registration.google.client-secret=

# spring.security.oauth2.client.registration.github.client-id=
# spring.security.oauth2.client.registration.github.client-secret=