spring.application.name=planchella
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/planchella
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=update

 spring.security.oauth2.client.registration.google.client-id=493505072228-l3nc8pvhbqjanr5gvmhepv4havsrr47u.apps.googleusercontent.com
# spring.security.oauth2.client.registration.google.client-secret=

# spring.security.oauth2.client.registration.github.client-id=
# spring.security.oauth2.client.registration.github.client-secret=